### ISSUE TITLE
Broken?

### ISSUE THREAD

**Issue by Lunix46** [AdamMoses-GitHub/MMM-ImageSlideshow#4]
Downloaded the files to the /MagicMirror/modules/ and pasted your config in the MagicMirror/config.js Got this error (have not changed any thing in folder or code)

`Whoops! There was an uncaught exception...
{ Error: ENOENT: no such file or directory, scandir 'modules/MMM-ImageSlideshow/exampleImages '
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:576:28)
    at Class.gatherImageList (/home/pi/MagicMirror/modules/MMM-ImageSlideshow/node_helper.js:63:65)
    at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-ImageSlideshow/node_helper.js:114:34)
    at Socket.<anonymous> (/home/pi/MagicMirror/modules/node_modules/node_helper/index.js:113:11)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at /home/pi/MagicMirror/node_modules/socket.io/lib/socket.js:513:12
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'modules/MMM-ImageSlideshow/exampleImages ' }
`

**Comment by mizbanhadi** [comment]
hi, please change imagepaths: [modules/MMM-ImageSlideshow/exampleImages]
and it works

**Comment by djay07** [comment]
> hi, please change imagepaths: [modules/MMM-ImageSlideshow/exampleImages]
> and it works

even with the change its not working for me...

Edit:
It's not working if i put it as last module. If i put it in somewhere in between, it works.
